// import pkg from "../../package.json" assert { type: "json" };
// export const { version } = pkg;
export { ABIName } from "./abiconst.js";
export { abi as ABIArena, arenaConnect } from "./chaintrapabi.js";
export * from "./deriveaddress.js";
export * from "./gameevents.js";
export { Player } from "./player.js";
export { PlayerState } from "./playerstate.js";
export { StateRoster } from "./stateroster.js";
export { TxMemo } from "./txmemo.js";
