---
version: "3"
silent: true

env:
  CHAINTRAP_CONTRACTS_DIR: "../chaintrap-contracts"
  CONTRACTS_DEVTOOL: "../chaintrap-contracts/scripts/devtool.sh"
vars:
  CURL_CICD_DEV: "curl -s -H 'Accept: application/vnd.github.v3.raw' -L https://api.github.com/repos/polysensus/cicd-dev-infra/contents"

tasks:
  bootstrap:
    desc: fetch the shared cicd development infra we use here
    cmds:
      - |
        {{.CURL_CICD_DEV}}/js/tusk-jspkg.yml?ref=main -O

  fmt:
    - npm run format
  format:
    desc: automatic code formatting - run prettier and then lint
    cmds:
      - |
        npm run format
        npm run lint

  build:
    desc: format and lint the code, then build the package
    deps: [format]
    cmds:
      - npm run build

  test:
    cmds:
      - task: test:unit

  deploy:
    desc: deploy the contracts to caimst and mumbai
    cmds:
      - task: deploy:caimst
      - task: deploy:mumbai

  find:mumbai:
    desc: "find the arena diamond on polygon mumba"
    cmds:
      - tusk -q -f tusk-arena.yml find-mumbai

  find:caimst:
    desc: "find the arena diamond on caimst"
    cmds:
      - tusk -q -f tusk-arena.yml find-caimst

  find:hh:
    desc: "find the arena diamond on hardhat"
    cmds:
      - tusk -q -f tusk-arena.yml find-hh

  deploy:caimst:
    desc: deploy the contracts to caimst and mumbai
    cmds:
      - tusk -f tusk-arena.yml deploy-caimst
  deploy:mumbai:
    desc: deploy the contracts to polygon mumbai testnet
    cmds:
      - tusk -f tusk-arena.yml deploy-polygon --diamond-address 0xBCAEF1Bd82E444B68d9C47E14f22d623150CeFB5
  deploy:hh:
    desc: deploy the contracts to hardhata (assumes the local server is listening on 8545)
    cmds:
      - tusk -f tusk-arena.yml deploy-hh
  deploy:caimst-new:
    desc: deploy the contracts to caimst and mumbai
    cmds:
      - tusk -f tusk-arena.yml deploy-caimst-new
  deploy:mumbai-new:
    desc: deploy the contracts to polygon mumbai testnet
    cmds:
      - tusk -f tusk-arena.yml deploy-polygon-new
  deploy:hh-new:
    desc: deploy the contracts to hardhata (assumes the local server is listening on 8545)
    cmds:
      - tusk -f tusk-arena.yml deploy-hh-new

  test:unit:
    desc: run the unit tests
    cmds:
      - npm run test -- {{.CLI_ARGS}}

  test:unit:ci:
    desc: run the unit tests for the ci (juint output)
    cmds:
      - |
        set -e
        # npm run test -- --reporter junit --outputFile jest-junit.xml
        npm run test -- --coverage

  test:integ:deploy:
    desc: start hardhat and deploy contracts for test:integ
    cmds:
      - task: dev:hh:restart
      - |
        set -e
        tusk -q -f tusk-arena.yml deploy-hh-new
        tusk -q -f tusk-arena.yml find-hh | tee arenaproxy.addr

  dev:hh:start:
    desc: start a local hardhat node (if there isn't one running)
    cmds:
      - $CONTRACTS_DEVTOOL start-node -d .local/hh

  dev:hh:restart:
    desc: restart the local hardhat node
    deps: [dev:hh:stop]
    cmds:
      - task: dev:hh:start

  dev:hh:stop:
    desc: stop a local hardhat node (according to pid in .local/hh/hh-pid)
    cmds:
      - $CONTRACTS_DEVTOOL stop-node -d .local/hh
