---
version: "3"
silent: true

tasks:
  format:
    desc: automatic code formatting - run prettier and then lint
    cmds:
      - |
        npm run format
        npm run lint

  build:
    deps: [format]
