on:
  push:

name: ci

jobs:
  test:
    name: ci build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the arenastate repository
        uses: actions/checkout@v3
        with:
          repository: polysensus/chaintrap-arenastate
          submodules: recursive
          path: chaintrap-arenastate

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          scope: "@polysensus"
          registry-url: "https://registry.npmjs.org"

      - name: Install go-tusk and go-task
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin

          # go-task
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- \
            -d -b $GITHUB_WORKSPACE/bin

          # go-tusk
          curl -sL https://git.io/tusk | bash -s -- -b $GITHUB_WORKSPACE/bin latest
          chmod a+x $GITHUB_WORKSPACE/bin/tusk
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH

      - name: Install arenastate with localy checked out chaintrap-contracts

        run: |

          pushd chaintrap-arenastate

          task bootstrap

          grep chaintrap-contracts package.json
          grep chaintrap-contracts package-lock.json
          npm install

          find node_modules/@polysensus/chaintrap-contracts/ -type d
          find node_modules/@polysensus/chaintrap-contracts/abi -name '*.json'

      - name: build
        working-directory: chaintrap-arenastate
        run: |
          task build

      - name: test prepare
        working-directory: chaintrap-arenastate
        env:
          ARENASTATE_NFTSTORAGE_API_KEY: ${{ secrets.ARENASTATE_NFTSTORAGE_API_KEY }}
          ARENASTATE_OPENAI_API_KEY: ${{ secrets.ARENASTATE_OPENAI_API_KEY }}
        run: |
          ! grep -sq CHAINTRAP_CD .env && echo "CHAINTRAP_CD=true" >> .env
          task test:prepare:cd
          cat .env.test | grep ARENASTATE_

      - name: test
        working-directory: chaintrap-arenastate
        run: |
          task test

      - name: test cms3
        working-directory: chaintrap-arenastate
        run: |
          task hh:cms3:test

      - name: test cms4
        working-directory: chaintrap-arenastate
        run: |
          task hh:cms4:test
