name: 'Test Report'
on:
  workflow_run:
    workflows: ['ci']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Vitest results (jest compat)
          path: '*.xml'
          reporter: jest-junit
